language: node_js
node_js:
  - '0.10'
env:
  - NODE_ENV=development
  - NODE_ENV=production
branches:
  only:
  - dev
notifications:
  email:
    - aaronsky@skyaaron.com
before_install:
  - npm install -g coffee-script
  - npm install -g grunt-cli
  - gem install sass
install:
  - CURRENT_ENV="$(echo $NODE_ENV)"
  - echo "${CURRENT_ENV}"
  - export NODE_ENV=development
  - echo $NODE_ENV
  - npm install
  - export NODE_ENV="${CURRENT_ENV}"
  - echo $NODE_ENV
before_script:
  - cd node_modules/react-commits-graph
  - mkdir -p lib/ \
  - rm -rf lib/*.js \
  - coffee -cbo lib/ src/*.coffee
script:
  - grunt ci
  - npm test